---
title: "Error Propagation"
subtitle: "µ errors generated by CD% uncertainty"
author: "Tristan Caro"
date: "Last knitted `r format(Sys.Date(), '%d %b %Y')`"
output:
  html_document: 
    df_print: paged
    number_sections: yes
    toc: yes
    toc_float: true
    toc_depth: 3
    code_folding: show
editor_options:
  chunk_output_type: console # switch to 'inline' if preferred
---

# Setup

```{r "setup", message = FALSE}
# packages
library(tidyverse) # CRAN v1.3.1 


# global knitting options for code rendering
knitr::opts_chunk$set(
  collapse = TRUE, comment = "#>",
  dev = c("png", "pdf"),
  dev.args = list(pdf = list(encoding = "WinAnsi", useDingbats = FALSE)),
  fig.keep = "all",
  fig.path = file.path("plots", paste0(gsub("\\.[Rr]md", "", knitr::current_input()), "_"))
)
```


# Generate a test dataset
Turnover is calculated as below:

$$
\mu = - \frac{1}{t} \cdot (ln (\frac{F_T - a \cdot F_L}{F_0 - a \cdot F_L})
$$

or in R-speak:
```
gencalc <- function(a, FT, F0, FL, t) {
  case_when(
    t == 0 ~ NA_real_,
    TRUE ~ - (1/t)*(log((FT - a*FL)/(F0 - a*FL)))
  )
}

```
where
- a is assimilation factor (0<a<1),
- FL is the isotopic composition of the tracer
- F0 is the isotopic composition starting biomass (likely natural abundance)
- FT is the isotopic composition of the biomass at time t
- t is time


```{r}
gencalc <- function(a, FT, F0, FL, t) {
  case_when(
    t == 0 ~ NA_real_,
    TRUE ~ - (1/t)*(log((FT - a*FL)/(F0 - a*FL)))
  )
}

gencalc_default <- function(a = 0.5, FT, F0 = 0.000015, FL, t = 1) {
  case_when(
    t == 0 ~ NA_real_,
    TRUE ~ - (1/t)*(log((FT - a*FL)/(F0 - a*FL)))
  )
}
```

`rnorm(3, mean=10, sd=2)`

```{r}
# Set random number seed
set.seed(5)

df_40at2H <- tibble(
  f_t = rnorm(40, mean = 30, sd = 1),
  f_l = 40,
  t = 1,
  u_d = gencalc(a = 1, FT = f_t, F0 = 0.000015, FL = f_l, t = t)
)

df_5at2H <- tibble(
  f_t = rnorm(40, mean = 4, sd = 1),
  f_l = 5,
  t = 1,
  u_d = gencalc(a = 1, FT = f_t, F0 = 0.000015, FL = f_l, t = t)
)

df_10at2H <- tibble(
  f_t = rnorm(40, mean = 7, sd = 1),
  f_l = 10,
  t = 1,
  u_d = gencalc(a = 1, FT = f_t, F0 = 0.000015, FL = f_l, t = t)
)

df_20at2H <- tibble(
  f_t = rnorm(40, mean = 15, sd = 1),
  f_l = 20,
  t = 1,
  u_d = gencalc(a = 1, FT = f_t, F0 = 0.000015, FL = f_l, t = t)
)

```

# Vary across standard error

```{r}
sd2 <- tibble(
  f_t = rnorm(400, mean = 30, sd = 2),
  u_d = gencalc(a = 1, FT = f_t, F0 = 0.000015, FL = 40, t = 10),
  sd = 2
)

sd1 <- tibble(
  f_t = rnorm(400, mean = 30, sd = 1),
  u_d = gencalc(a = 1, FT = f_t, F0 = 0.000015, FL = 40, t = 10),
  sd = 1
)

sd05 <- tibble(
   f_t = rnorm(400, mean = 30, sd = 0.5),
   u_d = gencalc(a = 1, FT = f_t, F0 = 0.000015, FL = 40, t = 10),
   sd = 0.5
)

sd025 <- tibble(
  f_t = rnorm(400, mean = 30, sd = 0.25),
  u_d = gencalc(a = 1, FT = f_t, F0 = 0.000015, FL = 40, t = 10),
  sd = 0.25
)

error_at_at2H40 <- bind_rows(sd2, sd1, sd05, sd025)
```

```{r}
error_at_at2H40 %>% ggplot(aes(x = f_t,
                           color = as.factor(sd))) +
  geom_density() +
  theme_classic()
```


```{r}
error_at_at2H40 %>% 
  ggplot(aes(x = f_t,
             y = u_d,
             color = as.factor(sd))) +
  geom_point(alpha = 0.5) +
  geom_vline(xintercept = 30,
             color = "red") +
  facet_wrap(~sd) +
  labs(x = "2H %",
       y = "Turnover rate (d^-1)") +
  theme_classic()

```


```{r}
error_at_at2H40 %>% 
  ggplot(aes(x = as.factor(sd),
             y = u_d,
             color = as.factor(sd))) +
  geom_jitter(alpha = 0.5) +
  geom_boxplot() +
  theme_classic()

```


# Vary across label strength

```{r}

L40 <- tibble(
   f_t = rnorm(400, mean = 10, sd = 0.5),
   u_d = gencalc(a = 1, FT = f_t, F0 = 0.000015, FL = 40, t = 3),
   label = 40
)

L35 <- tibble(
   f_t = rnorm(400, mean = 10, sd = 0.5),
   u_d = gencalc(a = 1, FT = f_t, F0 = 0.000015, FL = 35, t = 3),
   label = 35
)

L30 <- tibble(
   f_t = rnorm(400, mean = 10, sd = 0.5),
   u_d = gencalc(a = 1, FT = f_t, F0 = 0.000015, FL = 30, t = 3),
   label = 30
)

L25 <- tibble(
   f_t = rnorm(400, mean = 10, sd = 0.5),
   u_d = gencalc(a = 1, FT = f_t, F0 = 0.000015, FL = 25, t = 3),
   label = 25
)

L20 <- tibble(
   f_t = rnorm(400, mean = 10, sd = 0.5),
   u_d = gencalc(a = 1, FT = f_t, F0 = 0.000015, FL = 20, t = 3),
   label = 20
)

error_across_label <- bind_rows(L40, L35, L30, L25, L20)


```


```{r}
error_across_label %>% 
  ggplot(aes(x = f_t,
             y = u_d,
             color = as.factor(label))) +
  geom_point()
```

